# Generated by Django 5.0.1 on 2024-02-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webpages',
            new_name='Webpage',
        ),
        migrations.RenameField(
            model_name='accessrecord',
            old_name='webpages',
            new_name='name',
        ),
    ]
